services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine

    ports:
      - "15672:15672"
      - "5672:5672"

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia

    networks:
      - work-queues

volumes:
  rabbitmq-data:

networks:
  work-queues:
    driver: bridge